### ISSUE TITLE
Should we have some sort of username system and/or with authentication or just keep it anonymous?

### ISSUE THREAD

**Issue by dylanalvarez1** [dylanalvarez1/Breakroom#10]
What are the merits of either?

**Comment by phillanges** [comment]
I think the username system is nice for alias. Especially if the boards are intended to include more than two people. It's hard to differentiate when it's all anonymous. 
If it's anonymous there is no way to know who you're talking to unless there is a pinging system.
You could have arbitrary username's assigned from an array as one enters a chat - just like how Google does with animals.

I think there's no need for authentication since we're just going to keep it at an alias level.

**Comment by dylanalvarez1** [comment]
So I guess the question is if we assign arbitrary names or let users choose their own?

**Comment by phillanges** [comment]
I think assigning a random username would be nice. We could have associated icons with each name. Otherwise if we allow them to choose the username it'd feel rehashed, maybe? It'd be interesting to try.

**Comment by dylanalvarez1** [comment]
I like this idea, seems like a fun side project for 2.0
